name: live_streaming_minigame
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.11.0
  zego_uikit_prebuilt_live_streaming: ^2.18.0
  zego_uikit_signaling_plugin: ^2.5.1

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_inappwebview: ^5.7.2+3
  dio: ^5.3.2
  encrypt: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  dart_code_metrics: any

flutter:
  uses-material-design: true

  assets:
    - assets/minigame/index.js
    - assets/minigame/index.html
